# Generated by Django 6.0.5 on 2026-05-12 16:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('mobile_money_transaction', 'Mobile Money Transaction'), ('orange_money_transaction', 'Orange Money Transaction'), ('lec_bill_payment', 'LEC Bill Payment'), ('telecom_service', 'Telecom Service'), ('loan_action', 'Loan Action'), ('susu_action', 'Susu Action'), ('payout_action', 'Payout Action'), ('customer_support', 'Customer Support'), ('other', 'Other')], default='other', max_length=50)),
                ('service_type', models.CharField(choices=[('mtn_mobile_money', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('lec_purchase', 'LEC Purchase'), ('loan', 'Loan'), ('digital_susu', 'Digital Susu'), ('sim_registration', 'SIM Registration'), ('forex_exchange', 'Forex Exchange'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
