# Generated by Django 6.0.5 on 2026-05-12 16:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.TextField()),
                ('duration_months', models.PositiveIntegerField(default=1)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('address', models.TextField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self Employed'), ('business_owner', 'Business Owner'), ('student', 'Student'), ('unemployed', 'Unemployed'), ('other', 'Other')], default='other', max_length=30, null=True)),
                ('employer_or_business_name', models.CharField(blank=True, max_length=200, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('id_type', models.CharField(blank=True, choices=[('national_id', 'National ID'), ('voter_id', 'Voter ID'), ('passport', 'Passport'), ('drivers_license', 'Driver License'), ('other', 'Other')], default='other', max_length=30, null=True)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor1_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guarantor1_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('guarantor1_address', models.TextField(blank=True, null=True)),
                ('guarantor1_occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('guarantor1_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantor2_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guarantor2_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('guarantor2_address', models.TextField(blank=True, null=True)),
                ('guarantor2_occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('guarantor2_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant_photo', models.ImageField(blank=True, null=True, upload_to='loan_applicants/')),
                ('id_document_photo', models.ImageField(blank=True, null=True, upload_to='loan_ids/')),
                ('collateral_document', models.FileField(blank=True, null=True, upload_to='loan_collateral/')),
                ('collateral_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_repayable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customers.customer')),
            ],
        ),
    ]
